### ISSUE TITLE
Add an explicit license

### ISSUE THREAD

**Issue by Bisaloo** [TRACE-LAC/epi-training-kit#2]
At the moment, it's not clear under which terms people can re-use the materials available here. An explicit license would be helpful.

If you're not sure which license to use, I would recommend CC-BY: https://choosealicense.com/licenses/cc-by-4.0/

**Comment by zmcucunuba** [comment]
Many thanks @Bisaloo. I just saw this issue and tried to add one but CC-BY 4.0 is not available, only the 1.0. 
@lgbermeo can you please check the more appropriate licence? It could be the same used for tutorials. Thx
