### ISSUE TITLE
add a english version of the modules/units figure

### ISSUE THREAD

**Issue by avallecam** [TRACE-LAC/epi-training-kit#3]
**Is your feature request related to a problem? Please describe.**
I want to reference the current version of your [ETK modules and units](https://github.com/epiverse-trace/epi-training-kit/blob/main/img/unidades.png). I found it an excellent reference to refer to [concept dependencies](https://github.com/epiverse-trace/tutorials/issues/19) between training units and homogenize them with [learning paths](https://github.com/epiverse-trace/epiverse-trace.github.io/pull/90).

**Describe the solution you'd like**
Add to the `img/` folder an English translation of the [`uniandes.png`](https://github.com/epiverse-trace/epi-training-kit/blob/main/img/unidades.png) figure only. All the text can be translated with accessible tools. If the raw file is accessible to edit with Windows or Online tools, I can do the edit, too!

Alternatively, we can refer to the [flipsnack version](https://www.flipsnack.com/breakfast2go/etk.html), if you prefer.

**Additional context**
I generated this fair enough translated figure with Google Translate that I can temporally refer to. I'll look at it with further detail to find any inaccurate translation.
![Screenshot 2023-09-18 232803](https://github.com/epiverse-trace/epi-training-kit/assets/21230390/c55f5796-6261-4801-9e4b-a9a96b23d40d)

**Comment by lgbermeo** [comment]
Thanks Andree, I just saw this. I will check the translation and if you like I will also share the image with the English typography.

**Comment by Bisaloo** [comment]
I think this is now fixed by https://github.com/epiverse-trace/epi-training-kit/commit/3d4ab04dd9cd760349a289d3be1ebe264cc708f5.

The image is here: https://github.com/epiverse-trace/epi-training-kit/blob/main/img/Modules.jpg.

**Comment by avallecam** [comment]
yes, thanks!
