### ISSUE TITLE
Typo in Figure 1

### ISSUE THREAD

**Issue by adamkucharski** [TRACE-LAC/epi-training-kit#5]
These units looks great. Just noticed that there's a typo in [Figure 1 here](https://epiverse-trace.github.io/epi-training-kit/index-EN.html) – Markdwon should be Markdown:

![Modules](https://github.com/user-attachments/assets/c3d88da1-aeb8-4343-926b-75881c609a98)

**Comment by Joskerus** [comment]
Thanks, Adam. We already solved the typo, but I forgot to answer you.
